---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(tidyverse)

data("ny_noaa")
ny_noaa <- ny_noaa |>
  janitor::clean_names() |>
  mutate(
    tmax = as.numeric(tmax) / 10,
    tmin = as.numeric(tmin) / 10,
    prcp = prcp / 10
  ) |>
  separate(col = "date", into = c("year", "month", "day"), sep = "-") |>
  filter(year %in% c("2000","2001","2002")
  )

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
ny_noaa |>
  group_by(year, month) |>
  summarise(avg_snwd = mean(snwd, na.rm = TRUE)) |>
  plot_ly(x = ~year, y = ~month, z = ~avg_snwd, type = "heatmap", colors = "Blues") |>
  layout(title = "Average Monthly Snow Depth", 
         xaxis = list(title = "Year"), 
         yaxis = list(title = "Month"))

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
ny_noaa |>
  filter(month == "12") |>
  plot_ly(x = ~snow, y = ~tmin, z = ~tmax, type = "scatter3d", mode = "markers") |>
  layout(
    title = "3D Scatter Plot of Snow, Minimum, and Maximum Temperatures in December",
    scene = list(
      xaxis = list(title = "Snow (cm)"),
      yaxis = list(title = "Minimum Temperature (°C)"),
      zaxis = list(title = "Maximum Temperature (°C)")
    )
  )
```

### Chart C

```{r}
ny_noaa |>
  plot_ly (x = ~year, y = ~tmin, type = "box") |>
  layout(
    title = "Minimum Temperature Distribution by Year",
    yaxis = list(title = "Minimum Temperature (°C)"),
    xaxis = list(title = "Year")
    )
```

